name: validate-pull-request
on:
  - pull_request
jobs:
  format-source-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Get unformatted files
        id: changes
        run: |
          # Fetch changed files
          CHANGED_FILES=$(git diff -z --name-only --diff-filter=ACMRT origin/${{ github.event.pull_request.base.ref }}...origin/${{ github.event.pull_request.head.ref }})

          # Echo all changed files to the console
          echo "Changed files in this PR:"
          echo "$CHANGED_FILES"

          # Run Prettier only on relevant file types
          echo "$CHANGED_FILES" | \
          grep -E '\.(js|ts|jsx|tsx|json|css|scss|html|md|cls|apexc|trigger|apex|cmp|page|component|-meta\.xml)$' | \
          xargs -0 -I {} npx prettier --write "{}"

      - name: Commit formatted files
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "chore: format source code with Prettier"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
